spring.application.name=iakobos

spring.datasource.url=jdbc:postgresql://localhost:5432/iakobos
spring.datasource.username=thiago
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Caminho para acessar a interface grafica (UI)
springdoc.swagger-ui.path=/swagger-ui.html

# Caminho onde o JSON bruto da documentacao fica disponivel
springdoc.api-docs.path=/api-docs

api.security.token.secret=${JWT_SECRET}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
