spring.application.name=iakobos

spring.datasource.url=jdbc:postgresql://localhost:5432/iakobos
spring.datasource.username=thiago
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Caminho para acessar a interface gráfica (UI)
springdoc.swagger-ui.path=/swagger-ui.html

# Caminho onde o JSON bruto da documentação fica disponível
springdoc.api-docs.path=/api-docs